spring:
  application:
    name: file
  servlet:
    multipart:
      max-file-size: 15MB

server:
  port: 9003
  servlet:
    context-path: /file

eureka:
  client:
    service-url:http://127.0.0.1:8761/eureka/

file:
  path: D:/project/courseFile/
  domain: http://127.0.0.1:9000/file/f/

