spring:
  application:
    name: file
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

server:
  port: 9003
  servlet:
    context-path: /file

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/


file:
  path: D:/project/courseFile/
  domain: http://127.0.0.1:9000/file/f/


oss:
  accessKeyId: LTAI5t98DnXBH1UP25yWhqTT
  accessKeySecret: LlPzqHwiBPSJ6b0rh7bnjYB804xulI
  endpoint: http://oss-cn-chengdu.aliyuncs.com
  domain: http://tang1303.oss-cn-chengdu.aliyuncs.com/
  bucket: tang1303

vod:
  accessKeyId: LTAI5tF1XxRCXWwWXfWqXRm7
  accessKeySecret: UEJPpLs9oOMFU0EUt0B3eVnXgdCBXN

