spring:
  application:
    name: server
  datasource:
    url: jdbc:mysql://localhost:3306/couurse?serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
    username: course
    password: root


server:
  port: 9001
  servlet:
    context-path: /system

mybatis:
  type-aliases-package: com.course.system.domain
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

eureka:
  client:
    service-url:http://127.0.0.1:8761/eureka/


