spring:

  datasource:
    url: jdbc:mysql://localhost:3306/couurse?serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
    username: course
    password: root

mybatis:
  type-aliases-package: com.course.system.domain
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:/mapper/**/*.xml




