spring:
  application:
    name: gateway
  cloud:
    gateway:

      routes:
        - id: system
#          uri: http://127.0.0.1:9001
          uri: lb://system
          predicates:
            - Path=/system/**
          filters:
            - LoginAdmin=true

        - id: business
#          uri: http://127.0.0.1:9002
          uri: lb://business
          predicates:
            - Path=/business/**
          filters:
            - LoginAdmin=true

        - id: business
#          uri: http://127.0.0.1:9003
          uri: lb://file
          predicates:
            - Path=/file/**
          filters:
            - LoginAdmin=true


server:
  port: 9000

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/


